export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR"
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS" 
export const UPDATE_PRODUCTS_ERROR= "UPDATE_PRODUCTS_ERROR"
export const DELETE_PRODUCTS = "DELETE_PRODUCTS"
export const ADD_PRODUCTS= "ADD_PRODUCTS"